const alimentsData = [
    {name: '1 egg', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g potatoes', mealType: ['Breakfast', 'Lunch']},
    {name: '100g tomatoes', mealType: ['Breakfast', 'Lunch']},
    {name: '100g bell peppers', mealType: ['Breakfast', 'Lunch']},
    {name: '100g eggplant', mealType: ['Dinner']},
    {name: '100g zucchini', mealType: ['Lunch', 'Dinner']},
    {name: '100g cabbage', mealType: ['Lunch']},
    {name: '100g spinach', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g parsley', mealType: ['Lunch']},
    {name: '100g cauliflower', mealType: ['Lunch', 'Dinner']},
    {name: '100g green beans', mealType: ['Lunch']},
    {name: '100g peas', mealType: ['Lunch']},
    {name: '100g beetroot', mealType: ['Lunch']},
    {name: '100g mushrooms', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g spinach', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g pumpkin', mealType: ['Lunch', 'Dinner']},
    {name: '100g parsnip', mealType: ['Lunch', 'Dinner']},
    {name: '100g radish', mealType: ['Lunch']},
    {name: '100g lettuce', mealType: ['Lunch']},
    {name: '100g dry beans', mealType: ['Lunch']},
    {name: '100g red peppers', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g cucumbers', mealType: ['Lunch', 'Breakfast', "Dinner"]},
    {name: '100g rocket', mealType: ['Lunch']},
    {name: '100g apples', mealType: ['Breakfast', 'Snack']},
    {name: '100g bananas', mealType: ['Breakfast', 'Snack']},
    {name: '100g oranges', mealType: ['Breakfast', 'Snack']},
    {name: '100g grapes', mealType: ['Breakfast', 'Snack']},
    {name: '100g strawberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g watermelon', mealType: ['Breakfast', 'Snack']},
    {name: '100g pineapple', mealType: ['Breakfast', 'Snack']},
    {name: '100g mangoes', mealType: ['Breakfast', 'Snack']},
    {name: '100g kiwi', mealType: ['Breakfast', 'Snack']},
    {name: '100g peaches', mealType: ['Breakfast', 'Snack']},
    {name: '100g pears', mealType: ['Breakfast', 'Snack']},
    {name: '100g cherries', mealType: ['Breakfast', 'Snack']},
    {name: '100g blueberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g raspberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g avocados', mealType: ['Breakfast', 'Lunch']},
    {name: '100g grapefruits', mealType: ['Breakfast', 'Snack']},
    {name: '100g papayas', mealType: ['Breakfast', 'Snack']},
    {name: '100g cranberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g apricots', mealType: ['Breakfast', 'Snack']},
    {name: '100g blackberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g figs', mealType: ['Breakfast', 'Snack']},
    {name: '100g passion fruit', mealType: ['Breakfast', 'Snack']},
    {name: '100g nectarines', mealType: ['Breakfast', 'Snack']},
    {name: '100g plums', mealType: ['Breakfast', 'Snack']},
    {name: '100g pomelos', mealType: ['Breakfast', 'Snack']},
    {name: '100g pomegranates', mealType: ['Breakfast', 'Snack']},
    {name: '100g mulberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g boysenberries', mealType: ['Breakfast', 'Snack']},
    {name: '100g clementines', mealType: ['Breakfast', 'Snack']},
    {name: '100g beef tenderloin', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef sirloin', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef fillet', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef ribs', mealType: ['Lunch', 'Dinner']},
    {name: '100g minced beef', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef schnitzel', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef meatball', mealType: ['Lunch', 'Dinner']},
    {name: '100g grilled beef', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef shawarma', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef sausages', mealType: ['Lunch', 'Dinner']},
    {name: '100g beef goulash', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken breast', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken thighs', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken wings', mealType: ['Lunch', 'Dinner', 'Snack']},
    {name: '100g chicken hearts', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken liver', mealType: ['Lunch', 'Dinner']},
    {name: '100g minced chicken', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken tenderloin', mealType: ['Lunch', 'Dinner']},
    {name: '100g chicken skewers', mealType: ['Lunch', 'Dinner']},
    {name: '100g grilled chicken breast', mealType: ['Lunch', 'Dinner']},
    {name: '100g grilled chicken skewers', mealType: ['Lunch', 'Dinner']},
    {name: '100g grilled chicken tenderloin', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork leg', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork chop', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork ribs', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork neck', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork sausages', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork tenderloin', mealType: ['Lunch', 'Dinner']},
    {name: '100g minced pork', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork knuckle', mealType: ['Lunch', 'Dinner']},
    {name: '100g pork crest', mealType: ['Lunch', 'Dinner']},
    {name: '100g grilled pork chop', mealType: ['Lunch', 'Dinner']},
    {name: '100g salmon', mealType: ['Lunch', 'Dinner']},
    {name: '100g trout', mealType: ['Lunch', 'Dinner']},
    {name: '100g carp', mealType: ['Lunch', 'Dinner']},
    {name: '100g mackerel', mealType: ['Lunch', 'Dinner']},
    {name: '100g sardines', mealType: ['Lunch', 'Dinner']},
    {name: '100g anchovies', mealType: ['Lunch', 'Dinner']},
    {name: '100g herring', mealType: ['Lunch', 'Dinner']},
    {name: '100g tuna', mealType: ['Lunch', 'Dinner']},
    {name: '100g cod', mealType: ['Lunch', 'Dinner']},
    {name: '100g catfish', mealType: ['Lunch', 'Dinner']},
    {name: '100g perch', mealType: ['Lunch', 'Dinner']},
    {name: '100g sea bream', mealType: ['Lunch', 'Dinner']},
    {name: '30g almonds', mealType: ['Snack']},
    {name: '30g walnuts', mealType: ['Snack']},
    {name: '30g peanuts', mealType: ['Snack']},
    {name: '30g sunflower seeds', mealType: ['Snack']},
    {name: '30g pumpkin seeds', mealType: ['Snack']},
    {name: '100g milk', mealType: ['Breakfast', 'Snack']},
    {name: '100g cheese', mealType: ['Lunch', 'Dinner', 'Snack']},
    {name: '100g cream', mealType: ['Breakfast', 'Snack']},
    {name: '100g sour cream', mealType: ['Lunch', 'Dinner']},
    {name: '100g cottage cheese', mealType: ['Breakfast']},
    {name: '100g condensed milk', mealType: ['Dinner']},
    {name: '100g whipped cream', mealType: ['Dinner']},
    {name: '100g feta cheese', mealType: ['Lunch']},
    {name: '100g mozzarella cheese', mealType: ['Lunch', 'Dinner', 'Breakfast', 'Snack']},
    {name: '100g ricotta cheese', mealType: ['Lunch', 'Dinner', 'Breakfast', 'Snack']},
    {name: '100g greek yogurt', mealType: ['Breakfast', 'Snack']},
    {name: '100g kefir', mealType: ['Breakfast', 'Snack']},
    {name: '100g cream cheese', mealType: ['Breakfast', 'Snack']},
    {name: '100g paneer cheese', mealType: ['Lunch', 'Dinner']},
    {name: '100g blue cheese', mealType: ['Snack']},
    {name: '100g camembert cheese', mealType: ['Lunch']},
    {name: '100ml orange juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml apple juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml grape juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml cranberry juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml pineapple juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml tomato juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml carrot juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml pomegranate juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml lemon juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml lime juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml grapefruit juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml mango juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml peach juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml pear juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml watermelon juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml coconut water', mealType: ['Breakfast', 'Snack']},
    {name: '100ml cherry juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml blueberry juice', mealType: ['Breakfast', 'Snack']},
    {name: '100ml raspberry juice', mealType: ['Breakfast', 'Snack']},
    {name: '100g rice', mealType: ['Lunch', 'Dinner']},
    {name: '100g quinoa', mealType: ['Lunch', 'Dinner']},
    {name: '100g couscous', mealType: ['Lunch', 'Dinner']},
    {name: '100g bulgur', mealType: ['Lunch', 'Dinner']},
    {name: '100g millet', mealType: ['Lunch', 'Dinner']},
    {name: '100g buckwheat', mealType: ['Lunch', 'Dinner']},
    {name: '100g lentils', mealType: ['Lunch', 'Dinner']},
    {name: '100g chickpeas', mealType: ['Lunch', 'Dinner']},
    {name: '100g black beans', mealType: ['Lunch', 'Dinner']},
    {name: '100g kidney beans', mealType: ['Lunch', 'Dinner']},
    {name: '100g soybeans', mealType: ['Lunch', 'Dinner']},
    {name: '100g split peas', mealType: ['Lunch', 'Dinner']},
    {name: '100g dried apricots', mealType: ['Breakfast', 'Snack', 'Dinner']},
    {name: '100g beef pastrami', mealType: ['Lunch', 'Dinner']},
    {name: '100g Sibiu salami', mealType: ['Lunch', 'Dinner']},
    {name: '100g smoked sausages', mealType: ['Lunch', 'Dinner']},
    {name: '100g Prague ham', mealType: ['Dinner']},
    {name: '100g smoked bacon', mealType: ['Breakfast', 'Lunch', 'Dinner']},
    {name: '100g homemade liver sausage', mealType: ['Dinner']},
    {name: '100g Italian pancetta', mealType: ['Dinner']},
    {name: '100g Italian mortadella', mealType: ['Dinner']},
    {name: '100g cooked prosciutto', mealType: ['Dinner']},
    {name: '100g raw prosciutto', mealType: ['Dinner']},
    {name: '100g American pepperoni', mealType: ['Dinner']},
    {name: '100g white bread', mealType: ['Breakfast', 'Lunch']},
    {name: '100g whole wheat bread', mealType: ['Breakfast', 'Lunch']},
    {name: '100g rye bread', mealType: ['Breakfast', 'Lunch']},
    {name: '100g black bread', mealType: ['Breakfast', 'Lunch']},
    {name: '100g seeded bread', mealType: ['Breakfast', 'Lunch']},
    {name: '100g spaghetti', mealType: ['Dinner']},
    {name: '100g penne', mealType: ['Lunch', 'Dinner']},
    {name: '100g fusilli', mealType: ['Lunch', 'Dinner']},
    {name: '100g macaroni', mealType: ['Lunch', 'Dinner']},
    {name: '100g farfalle', mealType: ['Lunch', 'Dinner']},
]

export default alimentsData;